export default {
    CREATE_LOADEXPENSE: 'CREATE_LOADEXPENSE',
    UPDATE_LOADEXPENSE: 'UPDATE_LOADEXPENSE',
    DELETE_LOADEXPENSE: 'DELETE_LOADEXPENSE',
    SELECT_LOADEXPENSE: 'SELECT_LOADEXPENSE'
  };
  