export default {
    CREATE_LOADPAYMENT: 'CREATE_LOADPAYMENT',
    UPDATE_LOADPAYMENT: 'UPDATE_LOADPAYMENT',
    DELETE_LOADPAYMENT: 'DELETE_LOADPAYMENT',
    SELECT_LOADPAYMENT: 'SELECT_LOADPAYMENT'
  };
  