export default {
    CREATE_DRIVERSETTLEMENT: 'CREATE_DRIVERSETTLEMENT',
    UPDATE_DRIVERSETTLEMENT: 'UPDATE_DRIVERSETTLEMENT',
    DELETE_DRIVERSETTLEMENT: 'DELETE_DRIVERSETTLEMENT',
    SELECT_DRIVERSETTLEMENT: 'SELECT_DRIVERSETTLEMENT'
  };
  