export default {
    CREATE_TRANSPORTATION: 'CREATE_TRANSPORTATION',
    UPDATE_TRANSPORTATION: 'UPDATE_TRANSPORTATION',
    DELETE_TRANSPORTATION: 'DELETE_TRANSPORTATION',
    SELECT_TRANSPORTATION: 'SELECT_TRANSPORTATION'
  };
  