export default {
    CREATE_FINALIZELOADBILTY: 'CREATE_FINALIZELOADBILTY',
    UPDATE_FINALIZELOADBILTY: 'UPDATE_FINALIZELOADBILTY',
    DELETE_FINALIZELOADBILTY: 'DELETE_FINALIZELOADBILTY',
    SELECT_FINALIZELOADBILTY: 'SELECT_FINALIZELOADBILTY'
  };
  